name: ETL pipeline

on:
  push:
    branches:
      - main

jobs:
  ETL_Pipeline_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Execute Extract
        run: python Extract_data.py

      - name: Execute Transform
        run: python Transform_data.py
      
      - name: Execute Load
        run: python Load_data.py

      - name: Show Python Version
        run: python --version




